knp_paginator:
    page_range: 5                       # default page range used in pagination control
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using JOIN statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query parameter name
    template:
        pagination: '@KnpPaginator/Pagination/tailwind_pagination.html.twig'     # path to your custom pagination template, e.g. @KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # path to your custom sortable template
