# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # Make sure this matches your User entity identifier field

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider  # Changed to use your entity provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: admin_team_index  # Add your target route after login
                # Uncomment if your form uses different field names:
                # username_parameter: email
                # password_parameter: password
            logout:
                path: app_logout
                target: app_login  # Where to redirect after logout

    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: PUBLIC_ACCESS }

    role_hierarchy:  # Add this section for role inheritance
        ROLE_ADMIN: [ROLE_MANAGER, ROLE_COACH, ROLE_ATHLETE]
        ROLE_MANAGER: [ROLE_ATHLETE]
        ROLE_COACH: [ROLE_ATHLETE]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10