# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    facilities_directory: '%kernel.project_dir%/public/uploads/facilities'
    youtube_api_key: '%env(YOUTUBE_API_KEY)%'
    openweathermap_api_key: '%env(OPENWEATHERMAP_API_KEY)%' # Add this line correctly

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $kernelProjectDir: '%kernel.project_dir%'
            $uploadsDirectory: '%kernel.project_dir%/public/uploads/exercises'
            $facilitiesDirectory: '%facilities_directory%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\ExerciseController:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'

    App\Service\ExerciseApiService:
        arguments:
            $apiKey: '%env(EXERCISE_DB_API_KEY)%'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    App\Service\YouTubeService:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $params: '@parameter_bag'

    # Configure fixtures as services
    App\DataFixtures\:
        resource: '../src/DataFixtures'
        tags: ['doctrine.fixture.orm']

    App\DataFixtures\ExerciseFixtures:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $exerciseApi: '@App\Service\ExerciseApiService'

    App\Controller\Admin\ExerciseCrudController:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Validator\TrainingScheduleValidator:
        arguments: [ '@App\Repository\TrainingRepository' ]
        tags: [ validator.constraint_validator ]

